default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ooftypop-development
  username: postgres
  password: password
  host: localhost
  port: 5432
