# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a888a0ece326f7c40a0f75719702b585f1f32f98456413181bfe9acd405caa95483d9d9201696802958214f51d42497fc5201457031434d8106cf8ae0f806d

test:
  secret_key_base: f6a4f1e8ef99398a6526888e75345160735f8b977bb1aa0f3661cff4b50b0fd22683f2efdf2c2759a2812a03342b5d1ae6385bd8e1bf12acf1bc36aaf0de21e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
